[package]
name = "zox_rs"
version = "0.1.0"
edition = "2024"
license = "LICENSE.md"
description = "Support for zesh"
repository = "https://github.com/roberte777/zesh/zox_rs"

[dependencies]
thiserror = "2.0.11"
