name: Rust CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --workspace --all-targets

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run tests
        run: cargo test --workspace --all-targets
